/**
 * Unit tests for TextPreprocessor
 *
 * Epic 39: Tests text preprocessing for regex extraction.
 * Covers Guardian footer stripping, page marker removal,
 * and whitespace normalization.
 */

import { TextPreprocessor } from '../../../../src/infrastructure/extraction/TextPreprocessor'

describe('TextPreprocessor', () => {
  let preprocessor: TextPreprocessor

  beforeEach(() => {
    preprocessor = new TextPreprocessor()
  })

  describe('Guardian footer stripping', () => {
    it('should strip Guardian footer from text', () => {
      const input = [
        'Question 1.1',
        'What is your data governance policy?',
        'Response:',
        'We have a comprehensive policy.',
        '',
        'Generated by Guardian AI Vendor Assessment System',
        'Version 2.0 - Confidential',
        'Copyright 2026 Guardian',
      ].join('\n')

      const result = preprocessor.preprocess(input)

      expect(result).not.toContain('Generated by Guardian AI Vendor Assessment System')
      expect(result).not.toContain('Version 2.0')
      expect(result).not.toContain('Copyright 2026')
      expect(result).toContain('We have a comprehensive policy.')
    })

    it('should handle text without footer (no-op)', () => {
      const input = [
        'Question 1.1',
        'What is your data governance policy?',
        'Response:',
        'We have a comprehensive policy.',
      ].join('\n')

      const result = preprocessor.preprocess(input)

      expect(result).toBe(input)
    })
  })

  describe('pdf-parse page marker stripping', () => {
    it('should strip single page marker', () => {
      const input = 'Some text -- 1 of 5 -- more text'

      const result = preprocessor.preprocess(input)

      expect(result).toBe('Some text  more text')
    })

    it('should strip multiple page markers', () => {
      const input = [
        'Page one content -- 1 of 3 --',
        'Page two content -- 2 of 3 --',
        'Page three content -- 3 of 3 --',
      ].join('\n')

      const result = preprocessor.preprocess(input)

      expect(result).not.toContain('-- 1 of 3 --')
      expect(result).not.toContain('-- 2 of 3 --')
      expect(result).not.toContain('-- 3 of 3 --')
      expect(result).toContain('Page one content')
      expect(result).toContain('Page two content')
      expect(result).toContain('Page three content')
    })

    it('should strip markers with varied spacing', () => {
      const input = 'Before --  12  of  100  -- After'

      const result = preprocessor.preprocess(input)

      expect(result).toBe('Before  After')
    })
  })

  describe('whitespace normalization', () => {
    it('should normalize three or more consecutive newlines to two', () => {
      const input = 'Paragraph one\n\n\n\nParagraph two\n\n\n\n\nParagraph three'

      const result = preprocessor.preprocess(input)

      expect(result).toBe('Paragraph one\n\nParagraph two\n\nParagraph three')
    })

    it('should preserve double newlines (paragraph breaks)', () => {
      const input = 'Paragraph one\n\nParagraph two'

      const result = preprocessor.preprocess(input)

      expect(result).toBe('Paragraph one\n\nParagraph two')
    })

    it('should preserve single newlines', () => {
      const input = 'Line one\nLine two'

      const result = preprocessor.preprocess(input)

      expect(result).toBe('Line one\nLine two')
    })
  })

  describe('trimming', () => {
    it('should trim leading and trailing whitespace', () => {
      const input = '   \n\n  Some content  \n\n   '

      const result = preprocessor.preprocess(input)

      expect(result).toBe('Some content')
    })
  })

  describe('empty input', () => {
    it('should handle empty string input', () => {
      const result = preprocessor.preprocess('')

      expect(result).toBe('')
    })

    it('should handle whitespace-only input', () => {
      const result = preprocessor.preprocess('   \n\n\n   ')

      expect(result).toBe('')
    })
  })

  describe('combined operations', () => {
    it('should apply all preprocessing steps together', () => {
      const input = [
        '  ',
        '-- 1 of 2 -- Header content',
        '',
        '',
        '',
        '',
        'Question 1.1',
        'What is your policy?',
        'Response:',
        'Our policy is comprehensive. -- 2 of 2 --',
        '',
        '',
        '',
        '',
        'Generated by Guardian AI Vendor Assessment System',
        'Footer details',
        '  ',
      ].join('\n')

      const result = preprocessor.preprocess(input)

      // Page markers stripped
      expect(result).not.toContain('-- 1 of 2 --')
      expect(result).not.toContain('-- 2 of 2 --')
      // Footer stripped
      expect(result).not.toContain('Generated by Guardian AI Vendor Assessment System')
      expect(result).not.toContain('Footer details')
      // Excessive newlines normalized
      expect(result).not.toContain('\n\n\n')
      // Content preserved
      expect(result).toContain('Question 1.1')
      expect(result).toContain('Our policy is comprehensive.')
      // Trimmed
      expect(result).not.toMatch(/^\s/)
      expect(result).not.toMatch(/\s$/)
    })
  })
})
