/**
 * Question Domain Entity
 *
 * Represents a single assessment question generated by Claude
 * Organized by section and numbered within each section
 */

export type QuestionType = 'text' | 'enum' | 'boolean';

export interface QuestionMetadata {
  required?: boolean;
  helpText?: string;
  enumOptions?: string[];
}

export interface QuestionProps {
  id?: string;
  assessmentId: string;
  sectionName: string;
  sectionNumber: number;
  questionNumber: number;
  questionText: string;
  questionType: QuestionType;
  questionMetadata?: QuestionMetadata;
  createdAt?: Date;
}

export class Question {
  public readonly id?: string;
  public readonly assessmentId: string;
  public readonly sectionName: string;
  public readonly sectionNumber: number;
  public readonly questionNumber: number;
  public readonly questionText: string;
  public readonly questionType: QuestionType;
  public readonly questionMetadata?: QuestionMetadata;
  public readonly createdAt?: Date;

  private constructor(props: QuestionProps) {
    this.id = props.id;
    this.assessmentId = props.assessmentId;
    this.sectionName = props.sectionName;
    this.sectionNumber = props.sectionNumber;
    this.questionNumber = props.questionNumber;
    this.questionText = props.questionText;
    this.questionType = props.questionType;
    this.questionMetadata = props.questionMetadata;
    this.createdAt = props.createdAt;
  }

  /**
   * Create a new Question entity
   */
  static create(props: QuestionProps): Question {
    // Validation
    if (!props.assessmentId || props.assessmentId.trim() === '') {
      throw new Error('Assessment ID is required');
    }

    if (!props.sectionName || props.sectionName.trim() === '') {
      throw new Error('Section name is required');
    }

    if (props.sectionNumber < 1 || props.sectionNumber > 10) {
      throw new Error('Section number must be between 1 and 10');
    }

    if (props.questionNumber < 1) {
      throw new Error('Question number must be positive');
    }

    if (!props.questionText || props.questionText.length < 10) {
      throw new Error('Question text must be at least 10 characters');
    }

    // Validate enum questions have options
    if (
      props.questionType === 'enum' &&
      (!props.questionMetadata?.enumOptions ||
        props.questionMetadata.enumOptions.length === 0)
    ) {
      throw new Error('Enum questions must have enumOptions in metadata');
    }

    return new Question(props);
  }

  /**
   * Create Question from database persistence data
   */
  static fromPersistence(data: {
    id: string;
    assessmentId: string;
    sectionName: string;
    sectionNumber: number;
    questionNumber: number;
    questionText: string;
    questionType: QuestionType;
    questionMetadata?: QuestionMetadata | null;
    createdAt: Date;
  }): Question {
    return new Question({
      id: data.id,
      assessmentId: data.assessmentId,
      sectionName: data.sectionName,
      sectionNumber: data.sectionNumber,
      questionNumber: data.questionNumber,
      questionText: data.questionText,
      questionType: data.questionType,
      questionMetadata: data.questionMetadata || undefined,
      createdAt: data.createdAt,
    });
  }

  /**
   * Convert to database format
   */
  toPersistence(): {
    id?: string;
    assessmentId: string;
    sectionName: string;
    sectionNumber: number;
    questionNumber: number;
    questionText: string;
    questionType: QuestionType;
    questionMetadata?: QuestionMetadata;
  } {
    return {
      id: this.id,
      assessmentId: this.assessmentId,
      sectionName: this.sectionName,
      sectionNumber: this.sectionNumber,
      questionNumber: this.questionNumber,
      questionText: this.questionText,
      questionType: this.questionType,
      questionMetadata: this.questionMetadata,
    };
  }
}
