/**
 * TextPreprocessor - Pre-processes raw document text before regex extraction
 *
 * Epic 39: Cleans up raw text from PDF/DOCX parsing to improve
 * regex extraction accuracy. Handles Guardian-specific artifacts
 * (footers, page markers) and normalizes whitespace.
 *
 * Design constraints:
 * - Pure string operations, no external dependencies
 * - Idempotent: running twice produces the same result
 * - Preserves meaningful content structure (single newlines, paragraphs)
 */

/** Pattern: pdf-parse page markers like "-- 1 of 5 --" */
const PAGE_MARKER = /--\s*\d+\s*of\s*\d+\s*--/g

/** Pattern: Guardian system footer (everything from this line to end of document) */
const GUARDIAN_FOOTER = /Generated by Guardian AI Vendor Assessment System[\s\S]*$/

/** Pattern: Three or more consecutive newlines */
const EXCESSIVE_NEWLINES = /\n{3,}/g

export class TextPreprocessor {
  /**
   * Pre-process raw text for regex extraction
   *
   * Steps (in order):
   * 1. Strip pdf-parse page markers (e.g., "-- 3 of 12 --")
   * 2. Strip Guardian footer (from marker to end of document)
   * 3. Normalize excessive whitespace (3+ newlines become 2)
   * 4. Trim leading/trailing whitespace
   *
   * @param rawText - Raw text from document parser
   * @returns Cleaned text ready for regex extraction
   */
  preprocess(rawText: string): string {
    if (!rawText) {
      return ''
    }

    let text = rawText

    // 1. Strip pdf-parse page markers
    text = text.replace(PAGE_MARKER, '')

    // 2. Strip Guardian footer
    text = text.replace(GUARDIAN_FOOTER, '')

    // 3. Normalize excessive whitespace
    text = text.replace(EXCESSIVE_NEWLINES, '\n\n')

    // 4. Trim leading/trailing whitespace
    text = text.trim()

    return text
  }
}
