import {
  Document, Paragraph, TextRun, Footer, PageBreak, PageNumber,
  AlignmentType, Packer, convertInchesToTwip,
} from 'docx';
import { IScoringWordExporter } from '../../application/interfaces/IScoringWordExporter';
import { ScoringExportData } from '../../application/interfaces/IScoringPDFExporter';
import {
  BRAND_COLOR,
  createHeader,
  createScoreBanner,
  createExecutiveSummary,
  createKeyFindings,
  createDimensionTable,
  createNarrativeReport,
} from './WordSectionBuilders';
import { createISOAlignmentSection } from './WordISOBuilders';
import { ISO_DISCLAIMER } from '../../domain/compliance/isoMessagingTerms.js';

export class ScoringWordExporter implements IScoringWordExporter {
  async generateWord(data: ScoringExportData): Promise<Buffer> {
    const doc = new Document({
      styles: {
        paragraphStyles: [
          {
            id: 'Normal',
            name: 'Normal',
            run: { font: 'Segoe UI', size: 24 },
            paragraph: { spacing: { after: 120, line: 276 } },
          },
          {
            id: 'Heading1',
            name: 'Heading 1',
            basedOn: 'Normal',
            next: 'Normal',
            run: { font: 'Segoe UI', size: 36, bold: true, color: BRAND_COLOR },
            paragraph: { spacing: { before: 400, after: 200 } },
          },
          {
            id: 'Heading2',
            name: 'Heading 2',
            basedOn: 'Normal',
            next: 'Normal',
            run: { font: 'Segoe UI', size: 28, bold: true, color: '374151' },
            paragraph: { spacing: { before: 300, after: 150 } },
          },
        ],
      },
      sections: [{
        properties: {
          page: {
            margin: {
              top: convertInchesToTwip(1),
              right: convertInchesToTwip(1),
              bottom: convertInchesToTwip(1),
              left: convertInchesToTwip(1),
            },
          },
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({
                    text: `Generated by Guardian | Rubric: ${data.report.rubricVersion} | `,
                    size: 18,
                    color: '9CA3AF',
                  }),
                  new TextRun({ text: 'Page ', size: 18, color: '9CA3AF' }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 18, color: '9CA3AF' }),
                  new TextRun({ text: ' of ', size: 18, color: '9CA3AF' }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 18, color: '9CA3AF' }),
                ],
              }),
              new Paragraph({
                alignment: AlignmentType.CENTER,
                children: [
                  new TextRun({ text: ISO_DISCLAIMER, size: 16, color: '9CA3AF', italics: true }),
                ],
                spacing: { before: 100 },
              }),
            ],
          }),
        },
        children: [
          ...createHeader(data),
          ...createScoreBanner(data),
          ...createExecutiveSummary(data),
          ...createKeyFindings(data),
          // Page break before dimension table
          new Paragraph({ children: [new PageBreak()] }),
          ...createDimensionTable(data),
          ...createISOAlignmentSection(data),
          // Page break before narrative
          new Paragraph({ children: [new PageBreak()] }),
          ...createNarrativeReport(data),
        ],
      }],
    });

    return await Packer.toBuffer(doc);
  }
}
