import { create } from 'zustand';
import { persist } from 'zustand/middleware';
import { ChatMessage, EmbeddedComponent, ExportReadyPayload, QuestionnaireReadyPayload, ScoringCompletePayload, VendorClarificationNeededPayload, QuestionnaireProgressPayload } from '@/lib/websocket';
import type { Step } from '@/types/stepper';
import { GENERATION_STEPS } from '@/types/stepper';
import type { ScoringStatus, ScoringProgressEvent } from '@/types/scoring';

/**
 * Epic 32.2.1: Questionnaire progress state
 * Ephemeral UI state - NOT persisted to localStorage
 */
export interface QuestionnaireProgressState {
  message: string;
  step: number;
  totalSteps: number;
  timestamp: number;
  seq: number;
}

// Re-export for convenience
export { GENERATION_STEPS };

export interface Conversation {
  id: string;
  title: string;
  createdAt: Date;
  updatedAt: Date;
  mode: 'consult' | 'assessment' | 'scoring';
  /** Story 25.5: True while title is being generated by backend */
  titleLoading?: boolean;
  /** Story 25.3: True if user manually edited the title (prevents auto-update) */
  titleManuallyEdited?: boolean;
}

/**
 * Story 26.3: Timeout tracking for title loading shimmer
 * Stores timeout reference and start time for each conversation
 */
interface TitleLoadingState {
  timeout: ReturnType<typeof setTimeout>;
  startTime: number;
}

export interface ChatState {
  messages: ChatMessage[];
  isLoading: boolean;
  error: string | null;
  currentStreamingMessage: string | null;
  isStreaming: boolean;

  // Sidebar state
  sidebarOpen: boolean;
  sidebarMinimized: boolean;

  // Conversation management
  conversations: Conversation[];
  activeConversationId: string | null;
  newChatRequested: boolean; // Flag to request new conversation creation
  deleteConversationRequested: string | null; // Conversation ID to delete

  /**
   * Story 26.3: Track title loading timeouts
   * Map of conversationId -> { timeout, startTime }
   * NOTE: Map is used here because it's not persisted (Map doesn't serialize to localStorage well)
   */
  titleLoadingTimeouts: Map<string, TitleLoadingState>;

  /**
   * Story 25.6: ID of conversation currently being renamed inline
   * null when not editing any conversation title
   */
  editingConversationId: string | null;

  // Export readiness cache (per-conversation)
  exportReadyByConversation: Record<string, ExportReadyPayload>;

  // Scoring result cache (per-conversation) - Story 5c persistence
  scoringResultByConversation: Record<string, ScoringCompletePayload['result']>;

  /**
   * Pending questionnaire ready to be generated
   * Set when Claude calls questionnaire_ready tool
   * Cleared when user clicks Generate or changes conversation
   */
  pendingQuestionnaire: QuestionnaireReadyPayload | null;

  /**
   * Whether questionnaire generation is in progress
   * Used to show loading state on Generate button
   * Cleared on assistant_done or error event
   */
  isGeneratingQuestionnaire: boolean;

  /**
   * UI state for questionnaire prompt card (Story 4.3.1)
   * - 'hidden': No pending questionnaire
   * - 'ready': Prompt card visible, ready to generate
   * - 'generating': Generation in progress (loading state)
   * - 'download': Download buttons available
   * - 'error': Generation failed (retry available)
   */
  questionnaireUIState: 'hidden' | 'ready' | 'generating' | 'download' | 'error';

  /**
   * Error message when questionnaireUIState is 'error'
   * Null for all other states
   */
  questionnaireError: string | null;

  /**
   * Index in messages array where questionnaire should render (Story 14.1.2)
   * Set when questionnaire_ready event is received
   * Used to inject questionnaire into message list at correct position
   * -1 means append at end (legacy behavior)
   * NOTE: This is IN-MEMORY only - NOT persisted
   */
  questionnaireMessageIndex: number;

  /**
   * Story 14.1.5: Flag indicating questionnaire stream has completed
   * Used to gate download bubble visibility until streaming finishes
   * Reset to false on new questionnaire_ready, set true on stream complete
   */
  isQuestionnaireStreamComplete: boolean;

  /**
   * Generation steps for vertical stepper (Story 13.4.2)
   * Array of step definitions to display
   */
  generationSteps: Step[];

  /**
   * Current generation step index (Story 13.4.2)
   * -1 = idle/not started
   * 0-N = in progress (index of current step)
   * >= length = complete
   */
  currentGenerationStep: number;

  /**
   * Epic 15 Story 5a.7: Scoring progress state
   * Tracks current status of scoring analysis
   */
  scoringProgress: {
    status: ScoringStatus;
    message: string;
    progress?: number;
    error?: string;
  };

  /**
   * Epic 15 Story 5a.7: Scoring result (set on completion)
   * Contains composite score, dimension scores, and recommendations
   */
  scoringResult: ScoringCompletePayload['result'] | null;

  /**
   * Epic 18.4.2b: Vendor clarification state
   * Set when multiple vendors detected in uploaded files
   * Contains vendor options for user selection
   * Cleared when user selects a vendor or cancels
   */
  vendorClarification: VendorClarificationNeededPayload | null;

  /**
   * Story 24.5: Flag to simulate streaming for the next assistant message
   * Set when switching to assessment/scoring mode (guidance message)
   * Cleared after the message is rendered with streaming
   */
  simulateStreamingForNext: boolean;

  /**
   * Epic 32.2.1: Questionnaire generation progress (dimension-level feedback)
   * Ephemeral state - NOT persisted to localStorage
   * null = no progress yet or cleared
   */
  questionnaireProgress: QuestionnaireProgressState | null;

  /**
   * Epic 32.2.3: Reconnection state tracking
   * Used to preserve progress during reconnection
   */
  isReconnecting: boolean;

  addMessage: (message: ChatMessage) => void;
  setMessages: (messages: ChatMessage[]) => void;
  updateLastMessage: (content: string) => void;
  appendToLastMessage: (chunk: string) => void;
  appendComponentToLastAssistantMessage: (component: EmbeddedComponent) => void;
  startStreaming: () => void;
  finishStreaming: () => void;
  setLoading: (isLoading: boolean) => void;
  setError: (error: string | null) => void;
  clearMessages: () => void;

  // Sidebar actions
  toggleSidebar: () => void;
  setSidebarOpen: (open: boolean) => void;
  toggleSidebarMinimized: () => void;
  setSidebarMinimized: (minimized: boolean) => void;

  // Conversation management actions
  addConversation: (conversation: Conversation) => void;
  setActiveConversation: (id: string | null) => void;
  deleteConversation: (id: string) => void;
  removeConversationFromList: (id: string) => void;
  updateConversationTitle: (id: string, title: string) => void;
  setConversations: (conversations: Conversation[]) => void;
  requestNewChat: () => void;
  clearNewChatRequest: () => void;
  requestDeleteConversation: (id: string) => void;
  clearDeleteConversationRequest: () => void;

  /**
   * Story 25.6: Set which conversation is being edited (inline rename)
   * @param id - Conversation ID to edit, or null to clear editing state
   */
  setEditingConversationId: (id: string | null) => void;

  /**
   * Story 25.5: Set title loading state for a conversation
   * @param id - Conversation ID
   * @param loading - Whether title is being generated
   */
  setConversationTitleLoading: (id: string, loading: boolean) => void;

  /**
   * Story 25.6: Mark conversation title as manually edited
   * @param id - Conversation ID
   * @param edited - Whether title was manually edited
   */
  setConversationTitleManuallyEdited: (id: string, edited: boolean) => void;

  /**
   * Story 26.3: Start a timeout for title loading shimmer
   * If timeout fires, automatically clears the loading state
   * @param conversationId - Conversation ID
   */
  startTitleLoadingTimeout: (conversationId: string) => void;

  /**
   * Story 26.3: Clear the title loading timeout for a conversation
   * Called when title arrives or conversation is deleted
   * @param conversationId - Conversation ID
   */
  clearTitleLoadingTimeout: (conversationId: string) => void;

  /**
   * Story 26.3: Clear all title loading states older than 10 seconds
   * Called on app initialization to handle stale states from page reload
   */
  cleanupStaleTitleLoadingStates: () => void;

  /**
   * Story 26.3: Clear all title loading states (used for disconnect)
   * Called when WebSocket disconnects
   */
  clearAllTitleLoadingStates: () => void;

  // Export readiness actions
  setExportReady: (conversationId: string, payload: ExportReadyPayload) => void;
  clearExportReady: (conversationId: string) => void;
  getExportReady: (conversationId: string) => ExportReadyPayload | undefined;

  /**
   * Set pending questionnaire (from questionnaire_ready event)
   */
  setPendingQuestionnaire: (payload: QuestionnaireReadyPayload) => void;

  /**
   * Clear pending questionnaire (after generation or conversation change)
   */
  clearPendingQuestionnaire: () => void;

  /**
   * Set generation state (true when generating, false on completion/error)
   */
  setGenerating: (value: boolean) => void;

  /**
   * Set questionnaire UI state (Story 4.3.1)
   */
  setQuestionnaireUIState: (state: 'hidden' | 'ready' | 'generating' | 'download' | 'error') => void;

  /**
   * Set questionnaire error message (Story 4.3.1)
   */
  setQuestionnaireError: (error: string | null) => void;

  /**
   * Set questionnaire message position (Story 14.1.2)
   * @param index - Position in messages array, or -1 for end
   */
  setQuestionnaireMessageIndex: (index: number) => void;

  /**
   * Set current generation step (Story 13.4.2)
   * @param step - Step index (-1 to N, where N >= steps.length means complete)
   */
  setCurrentGenerationStep: (step: number) => void;

  /**
   * Reset generation step to -1 (idle) (Story 13.4.2)
   */
  resetGenerationStep: () => void;

  /**
   * Story 14.1.5: Set questionnaire stream complete flag
   * Called when streaming finishes to allow download bubble to render
   */
  setQuestionnaireStreamComplete: (value: boolean) => void;

  /**
   * Epic 15 Story 5a.7: Update scoring progress
   * Called when scoring_progress events are received
   */
  updateScoringProgress: (progress: Partial<ScoringProgressEvent>) => void;

  /**
   * Epic 15 Story 5a.7: Set scoring result
   * Called when scoring_complete event is received
   */
  setScoringResult: (result: ScoringCompletePayload['result'] | null) => void;

  /**
   * Epic 15 Story 5a.7: Reset scoring state
   * Called when starting new scoring or changing conversations
   */
  resetScoring: () => void;

  /**
   * Epic 15 Story 5c: Set scoring result for specific conversation (persistence)
   * Called when scoring_complete event is received
   */
  setScoringResultForConversation: (conversationId: string, result: ScoringCompletePayload['result']) => void;

  /**
   * Epic 15 Story 5c: Get scoring result for specific conversation
   */
  getScoringResultForConversation: (conversationId: string) => ScoringCompletePayload['result'] | undefined;

  /**
   * Epic 15 Story 5c: Clear scoring result for specific conversation
   */
  clearScoringResultForConversation: (conversationId: string) => void;

  /**
   * Epic 22.1.2: Rehydrate scoring result from backend
   * Called when conversation loads and no cached result exists
   * Updates both per-conversation cache and current scoringResult if active
   */
  rehydrateScoringResult: (conversationId: string, result: ScoringCompletePayload['result']) => void;

  /**
   * Epic 18.4.2b: Set vendor clarification (from vendor_clarification_needed event)
   */
  setVendorClarification: (payload: VendorClarificationNeededPayload) => void;

  /**
   * Epic 18.4.2b: Clear vendor clarification (after selection or cancel)
   */
  clearVendorClarification: () => void;

  /**
   * Story 24.5: Set flag to simulate streaming for the next assistant message
   * Called when switching to assessment/scoring mode
   */
  setSimulateStreamingForNext: (value: boolean) => void;

  /**
   * Epic 32.2.1: Set questionnaire progress
   * Includes ordering protection - rejects events with old seq
   * @param progress - Progress state or null to clear
   */
  setQuestionnaireProgress: (progress: QuestionnaireProgressState | null) => void;

  /**
   * Epic 32.2.3: Set reconnection state
   * @param value - Whether currently reconnecting
   */
  setReconnecting: (value: boolean) => void;
}

export const useChatStore = create<ChatState>()(
  persist(
    (set, get) => ({
      messages: [],
      isLoading: false,
      error: null,
      currentStreamingMessage: null,
      isStreaming: false,

      // Sidebar state - closed by default on all devices (mobile-first)
      sidebarOpen: false,
      sidebarMinimized: false,

      // Conversation management - defaults
      conversations: [],
      activeConversationId: null,
      newChatRequested: false,
      deleteConversationRequested: null,
      editingConversationId: null,

      // Story 26.3: Title loading timeout tracking
      titleLoadingTimeouts: new Map(),

      // Export readiness cache - defaults
      exportReadyByConversation: {},

      // Scoring result cache - defaults (Story 5c persistence)
      scoringResultByConversation: {},

      // Questionnaire generation - defaults
      pendingQuestionnaire: null,
      isGeneratingQuestionnaire: false,

      // Questionnaire UI state - defaults
      questionnaireUIState: 'hidden',
      questionnaireError: null,

      // Questionnaire position - defaults (Story 14.1.2)
      // NOTE: This is IN-MEMORY only - NOT persisted
      questionnaireMessageIndex: -1,

      // Story 14.1.5: Stream complete flag (gates download visibility)
      isQuestionnaireStreamComplete: false,

      // Stepper state - defaults (Story 13.4.2)
      generationSteps: GENERATION_STEPS,
      currentGenerationStep: -1,

      // Epic 15 Story 5a.7: Scoring state - defaults
      scoringProgress: {
        status: 'idle',
        message: '',
      },
      scoringResult: null,

      // Epic 18.4.2b: Vendor clarification - defaults
      vendorClarification: null,

      // Story 24.5: Simulated streaming flag - defaults
      simulateStreamingForNext: false,

      // Epic 32.2.1: Questionnaire progress - defaults (ephemeral)
      questionnaireProgress: null,

      // Epic 32.2.3: Reconnection state - defaults
      isReconnecting: false,

      addMessage: (message) =>
        set((state) => ({
          messages: [...state.messages, message],
        })),

      setMessages: (messages) => {
        console.log('[chatStore] setMessages called with', messages.length, 'messages');
        set({
          messages,
        });
        console.log('[chatStore] State updated with new messages');
      },

      updateLastMessage: (content) =>
        set((state) => {
          const messages = [...state.messages];
          if (messages.length > 0) {
            messages[messages.length - 1] = {
              ...messages[messages.length - 1],
              content,
            };
          }
          return { messages };
        }),

      appendToLastMessage: (chunk) =>
        set((state) => {
          const messages = [...state.messages];
          if (messages.length > 0) {
            const lastMessage = messages[messages.length - 1];
            messages[messages.length - 1] = {
              ...lastMessage,
              content: lastMessage.content + chunk,
            };
          }
          return { messages };
        }),

      appendComponentToLastAssistantMessage: (component) =>
        set((state) => {
          const messages = [...state.messages];
          // Find last assistant message
          for (let i = messages.length - 1; i >= 0; i--) {
            if (messages[i].role === 'assistant') {
              const existingComponents = messages[i].components || [];
              // Deduplicate: check if this component already exists
              const isDuplicate = existingComponents.some(
                (c) =>
                  c.type === component.type &&
                  c.data?.assessmentId === component.data?.assessmentId
              );
              if (isDuplicate) {
                console.log('[chatStore] Component already exists, skipping duplicate');
                return state; // No change
              }
              messages[i] = {
                ...messages[i],
                components: [...existingComponents, component],
              };
              break;
            }
          }
          return { messages };
        }),

      startStreaming: () =>
        set((state) => ({
          currentStreamingMessage: '',
          isStreaming: true,
          messages: [
            ...state.messages,
            {
              role: 'assistant',
              content: '',
              timestamp: new Date(),
            },
          ],
        })),

      finishStreaming: () =>
        set({
          currentStreamingMessage: null,
          isStreaming: false,
        }),

      setLoading: (isLoading) => set({ isLoading }),

      setError: (error) => set({ error }),

      clearMessages: () => {
        console.log('[chatStore] clearMessages called');
        set({ messages: [], error: null });
      },

      // Sidebar actions
      toggleSidebar: () =>
        set((state) => ({
          sidebarOpen: !state.sidebarOpen,
        })),

      setSidebarOpen: (open) =>
        set({
          sidebarOpen: open,
        }),

      toggleSidebarMinimized: () =>
        set((state) => ({
          sidebarMinimized: !state.sidebarMinimized,
        })),

      setSidebarMinimized: (minimized) =>
        set({
          sidebarMinimized: minimized,
        }),

      // Conversation management actions
      addConversation: (conversation) =>
        set((state) => {
          // CRITICAL FIX: Check if conversation already exists (deduplicate)
          const exists = state.conversations.some((c) => c.id === conversation.id);
          if (exists) {
            console.log('[chatStore] Conversation', conversation.id, 'already exists - skipping duplicate');
            return state; // No change - idempotent add
          }

          console.log('[chatStore] Adding new conversation:', conversation.id);
          return {
            conversations: [...state.conversations, conversation],
          };
        }),

      setActiveConversation: (id) => {
        // BUGFIX: Make idempotent - only clear state if conversation is actually changing
        // This prevents wiping rehydrated questionnaire state when WebSocket events
        // call setActiveConversation with the same ID after rehydration
        const currentId = get().activeConversationId;
        console.log('[chatStore] setActiveConversation:', { currentId, newId: id });
        if (currentId === id) {
          console.log('[chatStore] setActiveConversation called with same ID, skipping clear');
          return;
        }

        set({ activeConversationId: id });
        // Clear via action (DRY - uses same logic, enables future analytics)
        get().clearPendingQuestionnaire();
        // Also reset generation state
        get().setGenerating(false);
        // Reset stepper on conversation change (Story 13.4.2)
        get().resetGenerationStep();
        // Epic 32.2.1: Clear questionnaire progress on conversation switch
        set({ questionnaireProgress: null });
      },

      // Delete conversation immediately (used by tests and direct local operations)
      // For WebSocket-triggered deletes, use requestDeleteConversation instead
      // Story 26.3: Also clears any pending title loading timeout
      deleteConversation: (id) => {
        // Clear title loading timeout first to prevent memory leaks
        get().clearTitleLoadingTimeout(id);

        set((state) => ({
          conversations: state.conversations.filter((conv) => conv.id !== id),
          // Clear active conversation if it's the one being deleted
          activeConversationId: state.activeConversationId === id ? null : state.activeConversationId,
        }));
      },

      // Remove conversation from list after backend confirms deletion
      // Story 26.3: Also clears any pending title loading timeout
      removeConversationFromList: (id) => {
        // Clear title loading timeout first to prevent memory leaks
        get().clearTitleLoadingTimeout(id);

        set((state) => ({
          conversations: state.conversations.filter((conv) => conv.id !== id),
          // Clear active conversation if it's the one being deleted
          activeConversationId: state.activeConversationId === id ? null : state.activeConversationId,
        }));
      },

      updateConversationTitle: (id, title) =>
        set((state) => ({
          conversations: state.conversations.map((conv) =>
            conv.id === id ? { ...conv, title, updatedAt: new Date() } : conv
          ),
        })),

      setConversations: (conversations) => {
        console.log('[chatStore] setConversations called with', conversations.length, 'conversations');
        set({
          conversations,
        });
        console.log('[chatStore] State updated with new conversations');
      },

      requestNewChat: () => {
        console.log('[chatStore] New chat requested');
        set({ newChatRequested: true });
      },

      clearNewChatRequest: () => {
        console.log('[chatStore] Clearing new chat request');
        set({ newChatRequested: false });
      },

      requestDeleteConversation: (id) => {
        console.log('[chatStore] Delete conversation requested:', id);
        set({ deleteConversationRequested: id });
      },

      clearDeleteConversationRequest: () => {
        console.log('[chatStore] Clearing delete conversation request');
        set({ deleteConversationRequested: null });
      },

      // Story 25.6: Set which conversation is being edited
      setEditingConversationId: (id) => {
        console.log('[chatStore] Setting editing conversation:', id);
        set({ editingConversationId: id });
      },

      // Story 25.5: Set title loading state for a conversation
      // Story 26.3: Also manages timeout lifecycle
      setConversationTitleLoading: (id, loading) => {
        console.log('[chatStore] Setting title loading for conversation:', id, loading);

        if (loading) {
          // Start timeout when loading begins
          get().startTitleLoadingTimeout(id);
        } else {
          // Clear timeout when loading ends
          get().clearTitleLoadingTimeout(id);
        }

        set((state) => ({
          conversations: state.conversations.map((conv) =>
            conv.id === id ? { ...conv, titleLoading: loading } : conv
          ),
        }));
      },

      // Story 25.6: Mark conversation title as manually edited
      setConversationTitleManuallyEdited: (id, edited) => {
        console.log('[chatStore] Setting title manually edited for conversation:', id, edited);
        set((state) => ({
          conversations: state.conversations.map((conv) =>
            conv.id === id ? { ...conv, titleManuallyEdited: edited } : conv
          ),
        }));
      },

      // Story 26.3: Start a timeout for title loading shimmer (5 second hard timeout)
      startTitleLoadingTimeout: (conversationId) => {
        const state = get();

        // Idempotency: Don't start multiple timeouts for same conversation
        if (state.titleLoadingTimeouts.has(conversationId)) {
          console.log('[chatStore] Timeout already exists for conversation:', conversationId);
          return;
        }

        const startTime = Date.now();
        const timeout = setTimeout(() => {
          console.log('[chatStore] Title loading timeout fired for:', conversationId);
          // Clear the loading state
          get().setConversationTitleLoading(conversationId, false);
          // Note: clearTitleLoadingTimeout is called by setConversationTitleLoading(false)
        }, 5000); // 5 second hard timeout

        set((state) => {
          const newTimeouts = new Map(state.titleLoadingTimeouts);
          newTimeouts.set(conversationId, { timeout, startTime });
          return { titleLoadingTimeouts: newTimeouts };
        });

        console.log('[chatStore] Started title loading timeout for:', conversationId);
      },

      // Story 26.3: Clear the title loading timeout for a conversation
      clearTitleLoadingTimeout: (conversationId) => {
        const state = get();
        const existing = state.titleLoadingTimeouts.get(conversationId);

        if (existing) {
          clearTimeout(existing.timeout);
          set((state) => {
            const newTimeouts = new Map(state.titleLoadingTimeouts);
            newTimeouts.delete(conversationId);
            return { titleLoadingTimeouts: newTimeouts };
          });
          console.log('[chatStore] Cleared title loading timeout for:', conversationId);
        }
      },

      // Story 26.3: Clear all title loading states older than 10 seconds (stale cleanup)
      cleanupStaleTitleLoadingStates: () => {
        const state = get();
        const now = Date.now();
        const STALE_THRESHOLD_MS = 10000; // 10 seconds

        let clearedCount = 0;
        state.conversations.forEach((conv) => {
          if (conv.titleLoading) {
            const timeoutState = state.titleLoadingTimeouts.get(conv.id);
            const age = timeoutState ? now - timeoutState.startTime : STALE_THRESHOLD_MS + 1;

            // If older than threshold, clear it
            if (age > STALE_THRESHOLD_MS) {
              get().setConversationTitleLoading(conv.id, false);
              clearedCount++;
            }
          }
        });

        if (clearedCount > 0) {
          console.log('[chatStore] Cleaned up', clearedCount, 'stale title loading states');
        }
      },

      // Story 26.3: Clear all title loading states (used for disconnect)
      clearAllTitleLoadingStates: () => {
        const state = get();

        // Clear all timeouts
        state.titleLoadingTimeouts.forEach((timeoutState, conversationId) => {
          clearTimeout(timeoutState.timeout);
        });

        // Clear all titleLoading flags from conversations
        set((state) => ({
          titleLoadingTimeouts: new Map(),
          conversations: state.conversations.map((conv) =>
            conv.titleLoading ? { ...conv, titleLoading: false } : conv
          ),
        }));

        console.log('[chatStore] Cleared all title loading states');
      },

      // Export readiness actions
      setExportReady: (conversationId, payload) => {
        console.log('[chatStore] Setting export ready for conversation:', conversationId);
        set((state) => ({
          exportReadyByConversation: {
            ...state.exportReadyByConversation,
            [conversationId]: payload,
          },
        }));
      },

      clearExportReady: (conversationId) => {
        console.log('[chatStore] Clearing export ready for conversation:', conversationId);
        set((state) => {
          const { [conversationId]: _, ...rest } = state.exportReadyByConversation;
          return { exportReadyByConversation: rest };
        });
      },

      getExportReady: (conversationId) => {
        return get().exportReadyByConversation[conversationId];
      },

      // Questionnaire generation actions
      setPendingQuestionnaire: (payload) => {
        console.log('[chatStore] Setting pending questionnaire:', payload.conversationId);
        // Story 14.1.2: Capture current message count as insertion point
        const currentMessageCount = get().messages.length;
        set({
          pendingQuestionnaire: payload,
          questionnaireMessageIndex: currentMessageCount, // Insert after current messages
          // Story 14.1.5: Reset stream complete flag for new questionnaire
          isQuestionnaireStreamComplete: false,
        });
      },

      clearPendingQuestionnaire: () => {
        console.log('[chatStore] Clearing pending questionnaire');
        set({
          pendingQuestionnaire: null,
          questionnaireMessageIndex: -1,
          // Story 14.1.5: Reset stream complete flag
          isQuestionnaireStreamComplete: false,
        });
      },

      setGenerating: (value) => {
        console.log('[chatStore] Setting isGeneratingQuestionnaire:', value);
        set({ isGeneratingQuestionnaire: value });
      },

      // Questionnaire UI state actions (Story 4.3.1)
      setQuestionnaireUIState: (state) => {
        console.log('[chatStore] Setting questionnaireUIState:', state);
        set({ questionnaireUIState: state });
      },

      setQuestionnaireError: (error) => {
        console.log('[chatStore] Setting questionnaireError:', error);
        set({ questionnaireError: error });
      },

      // Story 14.1.2: Questionnaire position action
      setQuestionnaireMessageIndex: (index) => {
        console.log('[chatStore] Setting questionnaireMessageIndex:', index);
        set({ questionnaireMessageIndex: index });
      },

      // Stepper actions (Story 13.4.2)
      setCurrentGenerationStep: (step) => {
        console.log('[chatStore] Setting currentGenerationStep:', step);
        set({ currentGenerationStep: step });
      },

      resetGenerationStep: () => {
        console.log('[chatStore] Resetting generation step to -1');
        set({ currentGenerationStep: -1 });
      },

      // Story 14.1.5: Set questionnaire stream complete flag
      setQuestionnaireStreamComplete: (value) => {
        console.log('[chatStore] Setting isQuestionnaireStreamComplete:', value);
        set({ isQuestionnaireStreamComplete: value });
      },

      // Epic 15 Story 5a.7: Scoring state management
      updateScoringProgress: (progress) => {
        set((state) => ({
          scoringProgress: {
            ...state.scoringProgress,
            ...progress,
          },
        }));
      },

      setScoringResult: (result) => {
        set({ scoringResult: result });
      },

      resetScoring: () => {
        set({
          scoringProgress: {
            status: 'idle',
            message: '',
          },
          scoringResult: null,
        });
      },

      // Epic 15 Story 5c: Per-conversation scoring result persistence
      setScoringResultForConversation: (conversationId, result) => {
        console.log('[chatStore] Setting scoring result for conversation:', conversationId);
        set((state) => ({
          scoringResultByConversation: {
            ...state.scoringResultByConversation,
            [conversationId]: result,
          },
        }));
      },

      getScoringResultForConversation: (conversationId) => {
        return get().scoringResultByConversation[conversationId];
      },

      clearScoringResultForConversation: (conversationId) => {
        console.log('[chatStore] Clearing scoring result for conversation:', conversationId);
        set((state) => {
          const { [conversationId]: _, ...rest } = state.scoringResultByConversation;
          return { scoringResultByConversation: rest };
        });
      },

      // Epic 22.1.2: Rehydrate scoring result from backend
      rehydrateScoringResult: (conversationId, result) => {
        console.log('[chatStore] Rehydrating scoring result for conversation:', conversationId);
        set((state) => ({
          scoringResultByConversation: {
            ...state.scoringResultByConversation,
            [conversationId]: result,
          },
          // Also set the current scoringResult if this is the active conversation
          scoringResult: state.activeConversationId === conversationId ? result : state.scoringResult,
          scoringProgress: state.activeConversationId === conversationId
            ? { status: 'complete', message: 'Analysis complete!' }
            : state.scoringProgress,
        }));
      },

      // Epic 18.4.2b: Vendor clarification actions
      setVendorClarification: (payload) => {
        console.log('[chatStore] Setting vendor clarification:', payload.vendors.length, 'vendors');
        set({ vendorClarification: payload });
      },

      clearVendorClarification: () => {
        console.log('[chatStore] Clearing vendor clarification');
        set({ vendorClarification: null });
      },

      // Story 24.5: Simulated streaming flag action
      setSimulateStreamingForNext: (value) => {
        console.log('[chatStore] Setting simulateStreamingForNext:', value);
        set({ simulateStreamingForNext: value });
      },

      // Epic 32.2.1: Set questionnaire progress with ordering protection
      setQuestionnaireProgress: (progress) => {
        set((state) => {
          // Clearing progress - check reconnection state
          if (progress === null) {
            // Epic 32.2.3: Don't clear during reconnection
            if (state.isReconnecting) {
              console.log('[chatStore] Ignoring progress clear during reconnection');
              return state;
            }
            return { questionnaireProgress: null };
          }

          // Setting progress - apply ordering protection
          if (state.questionnaireProgress && progress.seq <= state.questionnaireProgress.seq) {
            console.log('[chatStore] Ignoring out-of-order progress event:', progress.seq, '<=', state.questionnaireProgress.seq);
            return state;
          }

          console.log('[chatStore] Setting questionnaireProgress:', progress.step, '/', progress.totalSteps, '-', progress.message);
          return { questionnaireProgress: progress };
        });
      },

      // Epic 32.2.3: Set reconnection state
      setReconnecting: (value) => {
        console.log('[chatStore] Setting isReconnecting:', value);
        set({ isReconnecting: value });
      },
    }),
    {
      name: 'guardian-chat-store',
      // Persist sidebar preferences and active conversation ID only
      // Conversations are NOT persisted - always fetched from backend per user
      partialize: (state) => ({
        sidebarMinimized: state.sidebarMinimized,
        activeConversationId: state.activeConversationId,
        // conversations NOT persisted - prevents showing other users' conversations
      }),
    }
  )
);
